### ISSUE TITLE
Consider switching from randombytes to some other dependency that does the same thing

### ISSUE THREAD

**Issue by gabrielmedici** [subins2000/p2pt#50]
randombytes@2.1.0 is causing problems with vite@3.1.2 and svelte@3.49.0 because of its use of "global.crypto" as seen on the trace below with the relevant code snippet from randombytes

```
browser.js:16 Uncaught ReferenceError: global is not defined
    at node_modules/.pnpm/randombytes@2.1.0/node_modules/randombytes/browser.js (browser.js:16:14)
    at __require (chunk-RSJERJUL.js?v=ff5c038d:3:50)
    at node_modules/.pnpm/simple-peer@9.11.1/node_modules/simple-peer/index.js (index.js:4:21)
    at __require (chunk-RSJERJUL.js?v=ff5c038d:3:50)
    at node_modules/.pnpm/bittorrent-tracker@9.19.0/node_modules/bittorrent-tracker/lib/client/websocket-tracker.js (websocket-tracker.js:3:14)
    at __require (chunk-RSJERJUL.js?v=ff5c038d:3:50)
    at node_modules/.pnpm/p2pt@1.5.1/node_modules/p2pt/p2pt.js (p2pt.js:7:26)
    at __require (chunk-RSJERJUL.js?v=ff5c038d:3:50)
    at dep:p2pt:1:16
node_modules/.pnpm/randombytes@2.1.0/node_modules/randombytes/browser.js @ browser.js:16
__require @ chunk-RSJERJUL.js?v=ff5c038d:3
node_modules/.pnpm/simple-peer@9.11.1/node_modules/simple-peer/index.js @ index.js:4
__require @ chunk-RSJERJUL.js?v=ff5c038d:3
node_modules/.pnpm/bittorrent-tracker@9.19.0/node_modules/bittorrent-tracker/lib/client/websocket-tracker.js @ websocket-tracker.js:3
__require @ chunk-RSJERJUL.js?v=ff5c038d:3
node_modules/.pnpm/p2pt@1.5.1/node_modules/p2pt/p2pt.js @ p2pt.js:7
__require @ chunk-RSJERJUL.js?v=ff5c038d:3
(anonymous) @ dep:p2pt:1
```

browser.js line 16
[the code on the randombytes repo](https://github.com/crypto-browserify/randombytes/blob/f18ded32b209f0d4c637608a11ae042ae96b4c2e/browser.js#L16)
```javascript
var crypto = global.crypto || global.msCrypto
```

since this library only uses randombytes to generate peer ids, i think it doesn't really need a library that uses the browser's crypto thing
but you guys did it that way for a reason, so if i'm wrong please correct me and explain why it's not the case :)

**Comment by gabrielmedici** [comment]
well f, in the heat of the moment i didn't notice that randombytes being a dependency of p2pt wasnt really the problem.

it seems the problem is that simple-peer uses it and bittorrent-tracker also uses it
sorry
